# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stroboPYgui(object):
    def setupUi(self, stroboPYgui):
        stroboPYgui.setObjectName("stroboPYgui")
        stroboPYgui.resize(1800, 900)
        self.centralWidget = QtWidgets.QWidget(stroboPYgui)
        self.centralWidget.setObjectName("centralWidget")
        self.tabs = QtWidgets.QTabWidget(self.centralWidget)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 1781, 841))
        self.tabs.setObjectName("tabs")
        self.hardware_tab = QtWidgets.QWidget()
        self.hardware_tab.setObjectName("hardware_tab")
        self.h_camera_box = QtWidgets.QGroupBox(self.hardware_tab)
        self.h_camera_box.setGeometry(QtCore.QRect(10, 10, 321, 121))
        self.h_camera_box.setObjectName("h_camera_box")
        self.h_camera_dd = QtWidgets.QComboBox(self.h_camera_box)
        self.h_camera_dd.setGeometry(QtCore.QRect(130, 30, 111, 23))
        self.h_camera_dd.setObjectName("h_camera_dd")
        self.label_49 = QtWidgets.QLabel(self.h_camera_box)
        self.label_49.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.label_49.setObjectName("label_49")
        self.h_connect_camera_btn = QtWidgets.QPushButton(self.h_camera_box)
        self.h_connect_camera_btn.setGeometry(QtCore.QRect(10, 60, 111, 23))
        self.h_connect_camera_btn.setObjectName("h_connect_camera_btn")
        self.h_disconnect_camera_btn = QtWidgets.QPushButton(self.h_camera_box)
        self.h_disconnect_camera_btn.setEnabled(False)
        self.h_disconnect_camera_btn.setGeometry(QtCore.QRect(130, 60, 111, 23))
        self.h_disconnect_camera_btn.setObjectName("h_disconnect_camera_btn")
        self.h_camera_status = QtWidgets.QLabel(self.h_camera_box)
        self.h_camera_status.setGeometry(QtCore.QRect(10, 90, 231, 21))
        self.h_camera_status.setFrameShape(QtWidgets.QFrame.Panel)
        self.h_camera_status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_camera_status.setObjectName("h_camera_status")
        self.h_use_ir_gain = QtWidgets.QCheckBox(self.h_camera_box)
        self.h_use_ir_gain.setGeometry(QtCore.QRect(250, 30, 71, 21))
        self.h_use_ir_gain.setObjectName("h_use_ir_gain")
        self.h_delay_box = QtWidgets.QGroupBox(self.hardware_tab)
        self.h_delay_box.setGeometry(QtCore.QRect(10, 140, 251, 121))
        self.h_delay_box.setObjectName("h_delay_box")
        self.h_delay_dd = QtWidgets.QComboBox(self.h_delay_box)
        self.h_delay_dd.setGeometry(QtCore.QRect(130, 30, 111, 23))
        self.h_delay_dd.setObjectName("h_delay_dd")
        self.label_50 = QtWidgets.QLabel(self.h_delay_box)
        self.label_50.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.label_50.setObjectName("label_50")
        self.h_connect_delay_btn = QtWidgets.QPushButton(self.h_delay_box)
        self.h_connect_delay_btn.setGeometry(QtCore.QRect(10, 60, 111, 23))
        self.h_connect_delay_btn.setObjectName("h_connect_delay_btn")
        self.h_disconnect_delay_btn = QtWidgets.QPushButton(self.h_delay_box)
        self.h_disconnect_delay_btn.setEnabled(False)
        self.h_disconnect_delay_btn.setGeometry(QtCore.QRect(130, 60, 111, 23))
        self.h_disconnect_delay_btn.setObjectName("h_disconnect_delay_btn")
        self.h_delay_status = QtWidgets.QLabel(self.h_delay_box)
        self.h_delay_status.setGeometry(QtCore.QRect(10, 90, 231, 21))
        self.h_delay_status.setFrameShape(QtWidgets.QFrame.Panel)
        self.h_delay_status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_delay_status.setObjectName("h_delay_status")
        self.tabs.addTab(self.hardware_tab, "")
        self.acquisition_tab = QtWidgets.QWidget()
        self.acquisition_tab.setObjectName("acquisition_tab")
        self.a_times_box = QtWidgets.QGroupBox(self.acquisition_tab)
        self.a_times_box.setGeometry(QtCore.QRect(10, 200, 341, 201))
        self.a_times_box.setStyleSheet("alternate-background-color: rgb(115, 115, 115);")
        self.a_times_box.setObjectName("a_times_box")
        self.a_distribution_dd = QtWidgets.QComboBox(self.a_times_box)
        self.a_distribution_dd.setGeometry(QtCore.QRect(10, 100, 91, 23))
        self.a_distribution_dd.setObjectName("a_distribution_dd")
        self.a_tstart_sb = QtWidgets.QDoubleSpinBox(self.a_times_box)
        self.a_tstart_sb.setGeometry(QtCore.QRect(10, 130, 91, 22))
        self.a_tstart_sb.setMinimum(-10.0)
        self.a_tstart_sb.setMaximum(10.0)
        self.a_tstart_sb.setProperty("value", -5.0)
        self.a_tstart_sb.setObjectName("a_tstart_sb")
        self.a_tend_sb = QtWidgets.QDoubleSpinBox(self.a_times_box)
        self.a_tend_sb.setGeometry(QtCore.QRect(10, 150, 91, 22))
        self.a_tend_sb.setMaximum(1000000.0)
        self.a_tend_sb.setSingleStep(100.0)
        self.a_tend_sb.setProperty("value", 100.0)
        self.a_tend_sb.setObjectName("a_tend_sb")
        self.a_num_tpoints_sb = QtWidgets.QSpinBox(self.a_times_box)
        self.a_num_tpoints_sb.setGeometry(QtCore.QRect(10, 170, 91, 22))
        self.a_num_tpoints_sb.setMinimum(20)
        self.a_num_tpoints_sb.setMaximum(5000)
        self.a_num_tpoints_sb.setSingleStep(10)
        self.a_num_tpoints_sb.setProperty("value", 100)
        self.a_num_tpoints_sb.setObjectName("a_num_tpoints_sb")
        self.a_timefile_cb = QtWidgets.QCheckBox(self.a_times_box)
        self.a_timefile_cb.setGeometry(QtCore.QRect(14, 30, 91, 21))
        self.a_timefile_cb.setObjectName("a_timefile_cb")
        self.a_timefile_btn = QtWidgets.QPushButton(self.a_times_box)
        self.a_timefile_btn.setGeometry(QtCore.QRect(130, 30, 91, 23))
        self.a_timefile_btn.setObjectName("a_timefile_btn")
        self.label_3 = QtWidgets.QLabel(self.a_times_box)
        self.label_3.setGeometry(QtCore.QRect(110, 100, 81, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.a_times_box)
        self.label_4.setGeometry(QtCore.QRect(110, 130, 59, 21))
        self.label_4.setObjectName("label_4")
        self.label_20 = QtWidgets.QLabel(self.a_times_box)
        self.label_20.setGeometry(QtCore.QRect(110, 150, 59, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.a_times_box)
        self.label_21.setGeometry(QtCore.QRect(110, 170, 111, 21))
        self.label_21.setObjectName("label_21")
        self.a_times_list = QtWidgets.QPlainTextEdit(self.a_times_box)
        self.a_times_list.setGeometry(QtCore.QRect(230, 30, 104, 161))
        self.a_times_list.setObjectName("a_times_list")
        self.a_timefile_list = QtWidgets.QComboBox(self.a_times_box)
        self.a_timefile_list.setGeometry(QtCore.QRect(10, 60, 211, 23))
        self.a_timefile_list.setObjectName("a_timefile_list")
        self.a_file_box = QtWidgets.QGroupBox(self.acquisition_tab)
        self.a_file_box.setEnabled(True)
        self.a_file_box.setGeometry(QtCore.QRect(10, 10, 341, 181))
        self.a_file_box.setObjectName("a_file_box")
        self.a_folder_btn = QtWidgets.QPushButton(self.a_file_box)
        self.a_folder_btn.setGeometry(QtCore.QRect(10, 30, 71, 23))
        self.a_folder_btn.setObjectName("a_folder_btn")
        self.a_metadata_pump_wavelength = QtWidgets.QLineEdit(self.a_file_box)
        self.a_metadata_pump_wavelength.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.a_metadata_pump_wavelength.setObjectName("a_metadata_pump_wavelength")
        self.a_metadata_pump_power = QtWidgets.QLineEdit(self.a_file_box)
        self.a_metadata_pump_power.setGeometry(QtCore.QRect(10, 130, 71, 20))
        self.a_metadata_pump_power.setObjectName("a_metadata_pump_power")
        self.a_metadata_pump_spotsize = QtWidgets.QLineEdit(self.a_file_box)
        self.a_metadata_pump_spotsize.setGeometry(QtCore.QRect(10, 150, 71, 20))
        self.a_metadata_pump_spotsize.setObjectName("a_metadata_pump_spotsize")
        self.label_65 = QtWidgets.QLabel(self.a_file_box)
        self.label_65.setGeometry(QtCore.QRect(90, 110, 71, 21))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.a_file_box)
        self.label_66.setGeometry(QtCore.QRect(90, 130, 47, 21))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.a_file_box)
        self.label_67.setGeometry(QtCore.QRect(90, 150, 61, 21))
        self.label_67.setObjectName("label_67")
        self.a_metadata_probe_wavelength = QtWidgets.QLineEdit(self.a_file_box)
        self.a_metadata_probe_wavelength.setGeometry(QtCore.QRect(180, 110, 71, 20))
        self.a_metadata_probe_wavelength.setObjectName("a_metadata_probe_wavelength")
        self.label_68 = QtWidgets.QLabel(self.a_file_box)
        self.label_68.setGeometry(QtCore.QRect(260, 110, 71, 21))
        self.label_68.setObjectName("label_68")
        self.a_metadata_probe_spotsize = QtWidgets.QLineEdit(self.a_file_box)
        self.a_metadata_probe_spotsize.setGeometry(QtCore.QRect(180, 150, 71, 20))
        self.a_metadata_probe_spotsize.setObjectName("a_metadata_probe_spotsize")
        self.label_69 = QtWidgets.QLabel(self.a_file_box)
        self.label_69.setGeometry(QtCore.QRect(260, 150, 71, 21))
        self.label_69.setObjectName("label_69")
        self.a_metadata_probe_power = QtWidgets.QLineEdit(self.a_file_box)
        self.a_metadata_probe_power.setGeometry(QtCore.QRect(180, 130, 71, 20))
        self.a_metadata_probe_power.setObjectName("a_metadata_probe_power")
        self.label_70 = QtWidgets.QLabel(self.a_file_box)
        self.label_70.setGeometry(QtCore.QRect(260, 130, 47, 21))
        self.label_70.setObjectName("label_70")
        self.a_filepath_le = QtWidgets.QLineEdit(self.a_file_box)
        self.a_filepath_le.setGeometry(QtCore.QRect(10, 60, 321, 23))
        self.a_filepath_le.setObjectName("a_filepath_le")
        self.a_filename_le = QtWidgets.QLineEdit(self.a_file_box)
        self.a_filename_le.setGeometry(QtCore.QRect(90, 30, 241, 23))
        self.a_filename_le.setObjectName("a_filename_le")
        self.label = QtWidgets.QLabel(self.a_file_box)
        self.label.setGeometry(QtCore.QRect(10, 90, 59, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.a_file_box)
        self.label_2.setGeometry(QtCore.QRect(180, 90, 59, 15))
        self.label_2.setObjectName("label_2")
        self.a_acquire_box = QtWidgets.QGroupBox(self.acquisition_tab)
        self.a_acquire_box.setGeometry(QtCore.QRect(10, 410, 341, 151))
        self.a_acquire_box.setObjectName("a_acquire_box")
        self.a_shortstage_t0 = QtWidgets.QDoubleSpinBox(self.a_acquire_box)
        self.a_shortstage_t0.setGeometry(QtCore.QRect(10, 30, 71, 22))
        self.a_shortstage_t0.setMinimum(-100000.0)
        self.a_shortstage_t0.setMaximum(100000.0)
        self.a_shortstage_t0.setObjectName("a_shortstage_t0")
        self.a_longstage_t0 = QtWidgets.QDoubleSpinBox(self.a_acquire_box)
        self.a_longstage_t0.setGeometry(QtCore.QRect(10, 50, 71, 22))
        self.a_longstage_t0.setMinimum(-1000000.0)
        self.a_longstage_t0.setMaximum(1000000.0)
        self.a_longstage_t0.setObjectName("a_longstage_t0")
        self.a_num_shots = QtWidgets.QSpinBox(self.a_acquire_box)
        self.a_num_shots.setGeometry(QtCore.QRect(10, 100, 71, 22))
        self.a_num_shots.setMinimum(50)
        self.a_num_shots.setMaximum(10000)
        self.a_num_shots.setObjectName("a_num_shots")
        self.label_5 = QtWidgets.QLabel(self.a_acquire_box)
        self.label_5.setGeometry(QtCore.QRect(90, 30, 141, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.a_acquire_box)
        self.label_6.setGeometry(QtCore.QRect(90, 50, 141, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.a_acquire_box)
        self.label_7.setGeometry(QtCore.QRect(90, 100, 121, 21))
        self.label_7.setObjectName("label_7")
        self.a_num_sweeps = QtWidgets.QSpinBox(self.a_acquire_box)
        self.a_num_sweeps.setGeometry(QtCore.QRect(10, 120, 71, 22))
        self.a_num_sweeps.setMinimum(1)
        self.a_num_sweeps.setMaximum(1000)
        self.a_num_sweeps.setObjectName("a_num_sweeps")
        self.label_8 = QtWidgets.QLabel(self.a_acquire_box)
        self.label_8.setGeometry(QtCore.QRect(90, 120, 121, 21))
        self.label_8.setObjectName("label_8")
        self.a_delaytype_dd = QtWidgets.QComboBox(self.a_acquire_box)
        self.a_delaytype_dd.setGeometry(QtCore.QRect(240, 40, 91, 22))
        self.a_delaytype_dd.setObjectName("a_delaytype_dd")
        self.label_9 = QtWidgets.QLabel(self.a_acquire_box)
        self.label_9.setGeometry(QtCore.QRect(240, 20, 91, 21))
        self.label_9.setObjectName("label_9")
        self.a_sweep_display = QtWidgets.QLCDNumber(self.a_acquire_box)
        self.a_sweep_display.setGeometry(QtCore.QRect(240, 80, 91, 23))
        self.a_sweep_display.setStyleSheet("color: rgb(255, 255, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.a_sweep_display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.a_sweep_display.setObjectName("a_sweep_display")
        self.label_16 = QtWidgets.QLabel(self.a_acquire_box)
        self.label_16.setGeometry(QtCore.QRect(240, 60, 91, 20))
        self.label_16.setObjectName("label_16")
        self.a_time_display = QtWidgets.QLCDNumber(self.a_acquire_box)
        self.a_time_display.setGeometry(QtCore.QRect(240, 120, 91, 23))
        self.a_time_display.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);")
        self.a_time_display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.a_time_display.setObjectName("a_time_display")
        self.label_17 = QtWidgets.QLabel(self.a_acquire_box)
        self.label_17.setGeometry(QtCore.QRect(240, 100, 91, 20))
        self.label_17.setObjectName("label_17")
        self.a_pinklaser_t0 = QtWidgets.QDoubleSpinBox(self.a_acquire_box)
        self.a_pinklaser_t0.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.a_pinklaser_t0.setMinimum(-1000000.0)
        self.a_pinklaser_t0.setMaximum(1000000.0)
        self.a_pinklaser_t0.setObjectName("a_pinklaser_t0")
        self.label_30 = QtWidgets.QLabel(self.a_acquire_box)
        self.label_30.setGeometry(QtCore.QRect(90, 70, 141, 21))
        self.label_30.setObjectName("label_30")
        self.a_calib_box = QtWidgets.QGroupBox(self.acquisition_tab)
        self.a_calib_box.setGeometry(QtCore.QRect(10, 570, 171, 151))
        self.a_calib_box.setObjectName("a_calib_box")
        self.a_calib_pixel_low = QtWidgets.QSpinBox(self.a_calib_box)
        self.a_calib_pixel_low.setGeometry(QtCore.QRect(10, 50, 71, 22))
        self.a_calib_pixel_low.setMaximum(1199)
        self.a_calib_pixel_low.setObjectName("a_calib_pixel_low")
        self.a_calib_wave_low = QtWidgets.QSpinBox(self.a_calib_box)
        self.a_calib_wave_low.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.a_calib_wave_low.setMinimum(200)
        self.a_calib_wave_low.setMaximum(2000)
        self.a_calib_wave_low.setProperty("value", 400)
        self.a_calib_wave_low.setObjectName("a_calib_wave_low")
        self.a_calib_pixel_high = QtWidgets.QSpinBox(self.a_calib_box)
        self.a_calib_pixel_high.setGeometry(QtCore.QRect(10, 100, 71, 22))
        self.a_calib_pixel_high.setMinimum(1)
        self.a_calib_pixel_high.setMaximum(1200)
        self.a_calib_pixel_high.setObjectName("a_calib_pixel_high")
        self.a_calib_wave_high = QtWidgets.QSpinBox(self.a_calib_box)
        self.a_calib_wave_high.setGeometry(QtCore.QRect(10, 120, 71, 22))
        self.a_calib_wave_high.setMinimum(200)
        self.a_calib_wave_high.setMaximum(2000)
        self.a_calib_wave_high.setProperty("value", 401)
        self.a_calib_wave_high.setObjectName("a_calib_wave_high")
        self.label_10 = QtWidgets.QLabel(self.a_calib_box)
        self.label_10.setGeometry(QtCore.QRect(90, 50, 81, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.a_calib_box)
        self.label_11.setGeometry(QtCore.QRect(90, 70, 71, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.a_calib_box)
        self.label_12.setGeometry(QtCore.QRect(90, 100, 81, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.a_calib_box)
        self.label_13.setGeometry(QtCore.QRect(90, 120, 71, 21))
        self.label_13.setObjectName("label_13")
        self.a_use_calib = QtWidgets.QCheckBox(self.a_calib_box)
        self.a_use_calib.setGeometry(QtCore.QRect(10, 30, 161, 17))
        self.a_use_calib.setAutoExclusive(False)
        self.a_use_calib.setObjectName("a_use_calib")
        self.a_launch_box = QtWidgets.QGroupBox(self.acquisition_tab)
        self.a_launch_box.setGeometry(QtCore.QRect(10, 730, 341, 71))
        self.a_launch_box.setObjectName("a_launch_box")
        self.a_run_btn = QtWidgets.QPushButton(self.a_launch_box)
        self.a_run_btn.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.a_run_btn.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.a_run_btn.setObjectName("a_run_btn")
        self.a_test_run_btn = QtWidgets.QCheckBox(self.a_launch_box)
        self.a_test_run_btn.setGeometry(QtCore.QRect(90, 30, 71, 31))
        self.a_test_run_btn.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.a_test_run_btn.setObjectName("a_test_run_btn")
        self.a_stop_btn = QtWidgets.QPushButton(self.a_launch_box)
        self.a_stop_btn.setGeometry(QtCore.QRect(170, 30, 71, 31))
        self.a_stop_btn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.a_stop_btn.setObjectName("a_stop_btn")
        self.groupBox_6 = QtWidgets.QGroupBox(self.acquisition_tab)
        self.groupBox_6.setGeometry(QtCore.QRect(1580, 9, 191, 81))
        self.groupBox_6.setObjectName("groupBox_6")
        self.a_plot_log_t_cb = QtWidgets.QCheckBox(self.groupBox_6)
        self.a_plot_log_t_cb.setGeometry(QtCore.QRect(20, 30, 82, 17))
        self.a_plot_log_t_cb.setAutoExclusive(False)
        self.a_plot_log_t_cb.setObjectName("a_plot_log_t_cb")
        self.groupBox_7 = QtWidgets.QGroupBox(self.acquisition_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(1580, 100, 191, 601))
        self.groupBox_7.setObjectName("groupBox_7")
        self.a_history = QtWidgets.QPlainTextEdit(self.groupBox_7)
        self.a_history.setGeometry(QtCore.QRect(10, 30, 171, 561))
        self.a_history.setObjectName("a_history")
        self.a_last_shot_graph = PlotWidget(self.acquisition_tab)
        self.a_last_shot_graph.setGeometry(QtCore.QRect(960, 20, 601, 391))
        self.a_last_shot_graph.setObjectName("a_last_shot_graph")
        self.a_spectra_graph = PlotWidget(self.acquisition_tab)
        self.a_spectra_graph.setGeometry(QtCore.QRect(960, 410, 601, 391))
        self.a_spectra_graph.setObjectName("a_spectra_graph")
        self.a_kinetic_graph = PlotWidget(self.acquisition_tab)
        self.a_kinetic_graph.setGeometry(QtCore.QRect(360, 410, 601, 391))
        self.a_kinetic_graph.setObjectName("a_kinetic_graph")
        self.a_colourmap = ImageView(self.acquisition_tab)
        self.a_colourmap.setGeometry(QtCore.QRect(360, 21, 601, 391))
        self.a_colourmap.setObjectName("a_colourmap")
        self.a_measurement_progress_bar = QtWidgets.QProgressBar(self.acquisition_tab)
        self.a_measurement_progress_bar.setGeometry(QtCore.QRect(1580, 780, 181, 23))
        self.a_measurement_progress_bar.setProperty("value", 0)
        self.a_measurement_progress_bar.setObjectName("a_measurement_progress_bar")
        self.a_cutoff_box = QtWidgets.QGroupBox(self.acquisition_tab)
        self.a_cutoff_box.setGeometry(QtCore.QRect(190, 570, 161, 151))
        self.a_cutoff_box.setObjectName("a_cutoff_box")
        self.a_use_cutoff = QtWidgets.QCheckBox(self.a_cutoff_box)
        self.a_use_cutoff.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.a_use_cutoff.setAutoExclusive(False)
        self.a_use_cutoff.setObjectName("a_use_cutoff")
        self.label_15 = QtWidgets.QLabel(self.a_cutoff_box)
        self.label_15.setGeometry(QtCore.QRect(90, 70, 61, 21))
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.a_cutoff_box)
        self.label_14.setGeometry(QtCore.QRect(90, 50, 61, 21))
        self.label_14.setObjectName("label_14")
        self.a_cutoff_pixel_high = QtWidgets.QSpinBox(self.a_cutoff_box)
        self.a_cutoff_pixel_high.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.a_cutoff_pixel_high.setMinimum(1)
        self.a_cutoff_pixel_high.setMaximum(1200)
        self.a_cutoff_pixel_high.setObjectName("a_cutoff_pixel_high")
        self.a_cutoff_pixel_low = QtWidgets.QSpinBox(self.a_cutoff_box)
        self.a_cutoff_pixel_low.setGeometry(QtCore.QRect(10, 50, 71, 22))
        self.a_cutoff_pixel_low.setMaximum(1199)
        self.a_cutoff_pixel_low.setObjectName("a_cutoff_pixel_low")
        self.a_sweep_progress_bar = QtWidgets.QProgressBar(self.acquisition_tab)
        self.a_sweep_progress_bar.setGeometry(QtCore.QRect(1580, 730, 181, 23))
        self.a_sweep_progress_bar.setProperty("value", 0)
        self.a_sweep_progress_bar.setObjectName("a_sweep_progress_bar")
        self.label_18 = QtWidgets.QLabel(self.acquisition_tab)
        self.label_18.setGeometry(QtCore.QRect(1580, 760, 181, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.acquisition_tab)
        self.label_19.setGeometry(QtCore.QRect(1580, 710, 181, 16))
        self.label_19.setObjectName("label_19")
        self.tabs.addTab(self.acquisition_tab, "")
        self.diagnostics_tab = QtWidgets.QWidget()
        self.diagnostics_tab.setObjectName("diagnostics_tab")
        self.d_refmanip_box = QtWidgets.QGroupBox(self.diagnostics_tab)
        self.d_refmanip_box.setGeometry(QtCore.QRect(10, 10, 341, 161))
        self.d_refmanip_box.setObjectName("d_refmanip_box")
        self.d_refman_vertical_stretch = QtWidgets.QDoubleSpinBox(self.d_refmanip_box)
        self.d_refman_vertical_stretch.setGeometry(QtCore.QRect(10, 50, 71, 22))
        self.d_refman_vertical_stretch.setMaximum(1200.0)
        self.d_refman_vertical_stretch.setObjectName("d_refman_vertical_stretch")
        self.d_use_ref_manip = QtWidgets.QCheckBox(self.d_refmanip_box)
        self.d_use_ref_manip.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.d_use_ref_manip.setAutoExclusive(False)
        self.d_use_ref_manip.setObjectName("d_use_ref_manip")
        self.label_42 = QtWidgets.QLabel(self.d_refmanip_box)
        self.label_42.setGeometry(QtCore.QRect(90, 50, 101, 21))
        self.label_42.setObjectName("label_42")
        self.d_refman_vertical_offset = QtWidgets.QDoubleSpinBox(self.d_refmanip_box)
        self.d_refman_vertical_offset.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.d_refman_vertical_offset.setMinimum(-60000.0)
        self.d_refman_vertical_offset.setMaximum(60000.0)
        self.d_refman_vertical_offset.setObjectName("d_refman_vertical_offset")
        self.d_refman_horiz_offset = QtWidgets.QDoubleSpinBox(self.d_refmanip_box)
        self.d_refman_horiz_offset.setGeometry(QtCore.QRect(10, 90, 71, 22))
        self.d_refman_horiz_offset.setMinimum(-1000.0)
        self.d_refman_horiz_offset.setMaximum(1000.0)
        self.d_refman_horiz_offset.setObjectName("d_refman_horiz_offset")
        self.d_refman_scale_center = QtWidgets.QDoubleSpinBox(self.d_refmanip_box)
        self.d_refman_scale_center.setGeometry(QtCore.QRect(10, 110, 71, 22))
        self.d_refman_scale_center.setMaximum(1200.0)
        self.d_refman_scale_center.setObjectName("d_refman_scale_center")
        self.d_refman_scale_factor = QtWidgets.QDoubleSpinBox(self.d_refmanip_box)
        self.d_refman_scale_factor.setGeometry(QtCore.QRect(10, 130, 71, 22))
        self.d_refman_scale_factor.setDecimals(3)
        self.d_refman_scale_factor.setMaximum(1200.0)
        self.d_refman_scale_factor.setObjectName("d_refman_scale_factor")
        self.label_43 = QtWidgets.QLabel(self.d_refmanip_box)
        self.label_43.setGeometry(QtCore.QRect(90, 70, 101, 21))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.d_refmanip_box)
        self.label_44.setGeometry(QtCore.QRect(90, 90, 101, 21))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.d_refmanip_box)
        self.label_45.setGeometry(QtCore.QRect(90, 110, 101, 21))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.d_refmanip_box)
        self.label_46.setGeometry(QtCore.QRect(90, 130, 101, 21))
        self.label_46.setObjectName("label_46")
        self.d_calib_box = QtWidgets.QGroupBox(self.diagnostics_tab)
        self.d_calib_box.setGeometry(QtCore.QRect(10, 180, 171, 151))
        self.d_calib_box.setObjectName("d_calib_box")
        self.d_calib_pixel_low = QtWidgets.QSpinBox(self.d_calib_box)
        self.d_calib_pixel_low.setGeometry(QtCore.QRect(10, 50, 71, 22))
        self.d_calib_pixel_low.setMaximum(1199)
        self.d_calib_pixel_low.setObjectName("d_calib_pixel_low")
        self.d_calib_wave_low = QtWidgets.QSpinBox(self.d_calib_box)
        self.d_calib_wave_low.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.d_calib_wave_low.setMinimum(200)
        self.d_calib_wave_low.setMaximum(2000)
        self.d_calib_wave_low.setProperty("value", 400)
        self.d_calib_wave_low.setObjectName("d_calib_wave_low")
        self.d_calib_pixel_high = QtWidgets.QSpinBox(self.d_calib_box)
        self.d_calib_pixel_high.setGeometry(QtCore.QRect(10, 100, 71, 22))
        self.d_calib_pixel_high.setMinimum(1)
        self.d_calib_pixel_high.setMaximum(1200)
        self.d_calib_pixel_high.setObjectName("d_calib_pixel_high")
        self.d_calib_wave_high = QtWidgets.QSpinBox(self.d_calib_box)
        self.d_calib_wave_high.setGeometry(QtCore.QRect(10, 120, 71, 22))
        self.d_calib_wave_high.setMinimum(200)
        self.d_calib_wave_high.setMaximum(2000)
        self.d_calib_wave_high.setProperty("value", 401)
        self.d_calib_wave_high.setObjectName("d_calib_wave_high")
        self.label_23 = QtWidgets.QLabel(self.d_calib_box)
        self.label_23.setGeometry(QtCore.QRect(90, 50, 101, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.d_calib_box)
        self.label_24.setGeometry(QtCore.QRect(90, 70, 71, 21))
        self.label_24.setObjectName("label_24")
        self.label_31 = QtWidgets.QLabel(self.d_calib_box)
        self.label_31.setGeometry(QtCore.QRect(90, 100, 101, 21))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.d_calib_box)
        self.label_32.setGeometry(QtCore.QRect(90, 120, 71, 21))
        self.label_32.setObjectName("label_32")
        self.d_use_calib = QtWidgets.QCheckBox(self.d_calib_box)
        self.d_use_calib.setGeometry(QtCore.QRect(10, 30, 151, 17))
        self.d_use_calib.setAutoExclusive(False)
        self.d_use_calib.setObjectName("d_use_calib")
        self.d_acquire_box = QtWidgets.QGroupBox(self.diagnostics_tab)
        self.d_acquire_box.setGeometry(QtCore.QRect(10, 460, 341, 161))
        self.d_acquire_box.setObjectName("d_acquire_box")
        self.d_shortstage_t0 = QtWidgets.QDoubleSpinBox(self.d_acquire_box)
        self.d_shortstage_t0.setGeometry(QtCore.QRect(10, 30, 71, 22))
        self.d_shortstage_t0.setMinimum(-100000.0)
        self.d_shortstage_t0.setMaximum(100000.0)
        self.d_shortstage_t0.setObjectName("d_shortstage_t0")
        self.d_longstage_t0 = QtWidgets.QDoubleSpinBox(self.d_acquire_box)
        self.d_longstage_t0.setGeometry(QtCore.QRect(10, 50, 71, 22))
        self.d_longstage_t0.setMinimum(-1000000.0)
        self.d_longstage_t0.setMaximum(1000000.0)
        self.d_longstage_t0.setObjectName("d_longstage_t0")
        self.label_35 = QtWidgets.QLabel(self.d_acquire_box)
        self.label_35.setGeometry(QtCore.QRect(90, 30, 141, 21))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.d_acquire_box)
        self.label_36.setGeometry(QtCore.QRect(90, 50, 141, 21))
        self.label_36.setObjectName("label_36")
        self.d_delaytype_dd = QtWidgets.QComboBox(self.d_acquire_box)
        self.d_delaytype_dd.setGeometry(QtCore.QRect(210, 130, 121, 22))
        self.d_delaytype_dd.setObjectName("d_delaytype_dd")
        self.label_39 = QtWidgets.QLabel(self.d_acquire_box)
        self.label_39.setGeometry(QtCore.QRect(210, 110, 81, 21))
        self.label_39.setObjectName("label_39")
        self.label_37 = QtWidgets.QLabel(self.d_acquire_box)
        self.label_37.setGeometry(QtCore.QRect(90, 100, 111, 21))
        self.label_37.setObjectName("label_37")
        self.d_num_shots = QtWidgets.QSpinBox(self.d_acquire_box)
        self.d_num_shots.setGeometry(QtCore.QRect(10, 100, 71, 22))
        self.d_num_shots.setMinimum(50)
        self.d_num_shots.setMaximum(10000)
        self.d_num_shots.setObjectName("d_num_shots")
        self.d_display_mode_spectra = QtWidgets.QComboBox(self.d_acquire_box)
        self.d_display_mode_spectra.setGeometry(QtCore.QRect(10, 130, 71, 22))
        self.d_display_mode_spectra.setObjectName("d_display_mode_spectra")
        self.label_41 = QtWidgets.QLabel(self.d_acquire_box)
        self.label_41.setGeometry(QtCore.QRect(90, 130, 111, 21))
        self.label_41.setObjectName("label_41")
        self.d_use_ir_gain = QtWidgets.QCheckBox(self.d_acquire_box)
        self.d_use_ir_gain.setGeometry(QtCore.QRect(260, 30, 71, 17))
        self.d_use_ir_gain.setObjectName("d_use_ir_gain")
        self.d_pinklaser_t0 = QtWidgets.QDoubleSpinBox(self.d_acquire_box)
        self.d_pinklaser_t0.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.d_pinklaser_t0.setMinimum(-1000000.0)
        self.d_pinklaser_t0.setMaximum(1000000.0)
        self.d_pinklaser_t0.setObjectName("d_pinklaser_t0")
        self.label_38 = QtWidgets.QLabel(self.d_acquire_box)
        self.label_38.setGeometry(QtCore.QRect(90, 70, 141, 16))
        self.label_38.setObjectName("label_38")
        self.d_dcshotfactor_sb = QtWidgets.QSpinBox(self.d_acquire_box)
        self.d_dcshotfactor_sb.setGeometry(QtCore.QRect(280, 80, 51, 22))
        self.d_dcshotfactor_sb.setMinimum(1)
        self.d_dcshotfactor_sb.setMaximum(10)
        self.d_dcshotfactor_sb.setObjectName("d_dcshotfactor_sb")
        self.label_22 = QtWidgets.QLabel(self.d_acquire_box)
        self.label_22.setGeometry(QtCore.QRect(220, 60, 111, 21))
        self.label_22.setObjectName("label_22")
        self.d_launch_box = QtWidgets.QGroupBox(self.diagnostics_tab)
        self.d_launch_box.setGeometry(QtCore.QRect(10, 730, 341, 71))
        self.d_launch_box.setObjectName("d_launch_box")
        self.d_run_btn = QtWidgets.QPushButton(self.d_launch_box)
        self.d_run_btn.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.d_run_btn.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.d_run_btn.setObjectName("d_run_btn")
        self.d_stop_btn = QtWidgets.QPushButton(self.d_launch_box)
        self.d_stop_btn.setGeometry(QtCore.QRect(90, 30, 71, 31))
        self.d_stop_btn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.d_stop_btn.setObjectName("d_stop_btn")
        self.d_other_box = QtWidgets.QGroupBox(self.diagnostics_tab)
        self.d_other_box.setGeometry(QtCore.QRect(10, 340, 341, 111))
        self.d_other_box.setObjectName("d_other_box")
        self.d_use_linear_corr = QtWidgets.QCheckBox(self.d_other_box)
        self.d_use_linear_corr.setGeometry(QtCore.QRect(10, 30, 161, 17))
        self.d_use_linear_corr.setObjectName("d_use_linear_corr")
        self.d_threshold_pixel = QtWidgets.QSpinBox(self.d_other_box)
        self.d_threshold_pixel.setGeometry(QtCore.QRect(150, 60, 71, 22))
        self.d_threshold_pixel.setMaximum(1200)
        self.d_threshold_pixel.setObjectName("d_threshold_pixel")
        self.label_51 = QtWidgets.QLabel(self.d_other_box)
        self.label_51.setGeometry(QtCore.QRect(230, 60, 101, 21))
        self.label_51.setObjectName("label_51")
        self.d_threshold_value = QtWidgets.QSpinBox(self.d_other_box)
        self.d_threshold_value.setGeometry(QtCore.QRect(150, 80, 71, 22))
        self.d_threshold_value.setMinimum(-10000000)
        self.d_threshold_value.setMaximum(10000000)
        self.d_threshold_value.setObjectName("d_threshold_value")
        self.label_52 = QtWidgets.QLabel(self.d_other_box)
        self.label_52.setGeometry(QtCore.QRect(230, 80, 101, 21))
        self.label_52.setObjectName("label_52")
        self.d_use_reference = QtWidgets.QCheckBox(self.d_other_box)
        self.d_use_reference.setGeometry(QtCore.QRect(10, 50, 151, 17))
        self.d_use_reference.setObjectName("d_use_reference")
        self.d_set_linear_corr_btn = QtWidgets.QPushButton(self.d_other_box)
        self.d_set_linear_corr_btn.setGeometry(QtCore.QRect(170, 30, 31, 21))
        self.d_set_linear_corr_btn.setObjectName("d_set_linear_corr_btn")
        self.d_use_avg_off_shots = QtWidgets.QCheckBox(self.d_other_box)
        self.d_use_avg_off_shots.setGeometry(QtCore.QRect(10, 70, 151, 17))
        self.d_use_avg_off_shots.setObjectName("d_use_avg_off_shots")
        self.d_max_dtt = QtWidgets.QDoubleSpinBox(self.d_other_box)
        self.d_max_dtt.setGeometry(QtCore.QRect(260, 30, 71, 22))
        self.d_max_dtt.setDecimals(4)
        self.d_max_dtt.setMinimum(-99.9)
        self.d_max_dtt.setSingleStep(1.1)
        self.d_max_dtt.setProperty("value", 1.0)
        self.d_max_dtt.setObjectName("d_max_dtt")
        self.label_53 = QtWidgets.QLabel(self.d_other_box)
        self.label_53.setGeometry(QtCore.QRect(210, 30, 51, 21))
        self.label_53.setObjectName("label_53")
        self.d_error_graph = PlotWidget(self.diagnostics_tab)
        self.d_error_graph.setGeometry(QtCore.QRect(360, 20, 701, 391))
        self.d_error_graph.setObjectName("d_error_graph")
        self.d_probe_ref_graph = PlotWidget(self.diagnostics_tab)
        self.d_probe_ref_graph.setGeometry(QtCore.QRect(360, 410, 701, 391))
        self.d_probe_ref_graph.setObjectName("d_probe_ref_graph")
        self.d_trigger_graph = PlotWidget(self.diagnostics_tab)
        self.d_trigger_graph.setGeometry(QtCore.QRect(1060, 20, 511, 391))
        self.d_trigger_graph.setObjectName("d_trigger_graph")
        self.d_last_shot_graph = PlotWidget(self.diagnostics_tab)
        self.d_last_shot_graph.setGeometry(QtCore.QRect(1060, 410, 511, 391))
        self.d_last_shot_graph.setObjectName("d_last_shot_graph")
        self.groupBox_17 = QtWidgets.QGroupBox(self.diagnostics_tab)
        self.groupBox_17.setGeometry(QtCore.QRect(1580, 10, 191, 791))
        self.groupBox_17.setObjectName("groupBox_17")
        self.d_history = QtWidgets.QPlainTextEdit(self.groupBox_17)
        self.d_history.setGeometry(QtCore.QRect(10, 30, 171, 751))
        self.d_history.setObjectName("d_history")
        self.d_cutoff_box = QtWidgets.QGroupBox(self.diagnostics_tab)
        self.d_cutoff_box.setGeometry(QtCore.QRect(190, 180, 161, 151))
        self.d_cutoff_box.setObjectName("d_cutoff_box")
        self.d_use_cutoff = QtWidgets.QCheckBox(self.d_cutoff_box)
        self.d_use_cutoff.setGeometry(QtCore.QRect(10, 30, 141, 17))
        self.d_use_cutoff.setAutoExclusive(False)
        self.d_use_cutoff.setObjectName("d_use_cutoff")
        self.label_33 = QtWidgets.QLabel(self.d_cutoff_box)
        self.label_33.setGeometry(QtCore.QRect(90, 50, 61, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.d_cutoff_box)
        self.label_34.setGeometry(QtCore.QRect(90, 70, 61, 21))
        self.label_34.setObjectName("label_34")
        self.d_cutoff_pixel_high = QtWidgets.QSpinBox(self.d_cutoff_box)
        self.d_cutoff_pixel_high.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.d_cutoff_pixel_high.setMinimum(1)
        self.d_cutoff_pixel_high.setMaximum(1200)
        self.d_cutoff_pixel_high.setProperty("value", 1)
        self.d_cutoff_pixel_high.setObjectName("d_cutoff_pixel_high")
        self.d_cutoff_pixel_low = QtWidgets.QSpinBox(self.d_cutoff_box)
        self.d_cutoff_pixel_low.setGeometry(QtCore.QRect(10, 50, 71, 22))
        self.d_cutoff_pixel_low.setMaximum(1199)
        self.d_cutoff_pixel_low.setObjectName("d_cutoff_pixel_low")
        self.d_times_box = QtWidgets.QGroupBox(self.diagnostics_tab)
        self.d_times_box.setGeometry(QtCore.QRect(10, 630, 341, 91))
        self.d_times_box.setObjectName("d_times_box")
        self.d_time = QtWidgets.QDoubleSpinBox(self.d_times_box)
        self.d_time.setGeometry(QtCore.QRect(10, 60, 81, 22))
        self.d_time.setMinimum(-1000000.0)
        self.d_time.setMaximum(1000000.0)
        self.d_time.setObjectName("d_time")
        self.d_move_to_time_btn = QtWidgets.QPushButton(self.d_times_box)
        self.d_move_to_time_btn.setGeometry(QtCore.QRect(100, 60, 91, 21))
        self.d_move_to_time_btn.setObjectName("d_move_to_time_btn")
        self.d_jogleft = QtWidgets.QPushButton(self.d_times_box)
        self.d_jogleft.setGeometry(QtCore.QRect(100, 30, 41, 20))
        self.d_jogleft.setObjectName("d_jogleft")
        self.d_jogright = QtWidgets.QPushButton(self.d_times_box)
        self.d_jogright.setGeometry(QtCore.QRect(150, 30, 41, 20))
        self.d_jogright.setObjectName("d_jogright")
        self.d_jogstep_sb = QtWidgets.QDoubleSpinBox(self.d_times_box)
        self.d_jogstep_sb.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.d_jogstep_sb.setMaximum(10.0)
        self.d_jogstep_sb.setSingleStep(0.01)
        self.d_jogstep_sb.setProperty("value", 0.01)
        self.d_jogstep_sb.setObjectName("d_jogstep_sb")
        self.d_set_current_btn = QtWidgets.QPushButton(self.d_times_box)
        self.d_set_current_btn.setGeometry(QtCore.QRect(200, 60, 131, 21))
        self.d_set_current_btn.setObjectName("d_set_current_btn")
        self.label_25 = QtWidgets.QLabel(self.diagnostics_tab)
        self.label_25.setGeometry(QtCore.QRect(370, 30, 191, 21))
        self.label_25.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.diagnostics_tab)
        self.label_26.setGeometry(QtCore.QRect(370, 50, 191, 21))
        self.label_26.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.diagnostics_tab)
        self.label_27.setGeometry(QtCore.QRect(370, 70, 191, 21))
        self.label_27.setStyleSheet("color: rgb(85, 255, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.tabs.addTab(self.diagnostics_tab, "")
        self.log_tab = QtWidgets.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.log = QtWidgets.QPlainTextEdit(self.log_tab)
        self.log.setGeometry(QtCore.QRect(10, 10, 1761, 791))
        self.log.setObjectName("log")
        self.tabs.addTab(self.log_tab, "")
        stroboPYgui.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(stroboPYgui)
        self.statusBar.setObjectName("statusBar")
        stroboPYgui.setStatusBar(self.statusBar)

        self.retranslateUi(stroboPYgui)
        self.tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(stroboPYgui)

    def retranslateUi(self, stroboPYgui):
        _translate = QtCore.QCoreApplication.translate
        stroboPYgui.setWindowTitle(_translate("stroboPYgui", "stroboPY"))
        self.h_camera_box.setTitle(_translate("stroboPYgui", "Camera Connections"))
        self.label_49.setText(_translate("stroboPYgui", "camera selection"))
        self.h_connect_camera_btn.setText(_translate("stroboPYgui", "connect"))
        self.h_disconnect_camera_btn.setText(_translate("stroboPYgui", "disconnect"))
        self.h_camera_status.setText(_translate("stroboPYgui", "ready to connect"))
        self.h_use_ir_gain.setText(_translate("stroboPYgui", "IR Gain"))
        self.h_delay_box.setTitle(_translate("stroboPYgui", "Delay Connections"))
        self.label_50.setText(_translate("stroboPYgui", "delay selection"))
        self.h_connect_delay_btn.setText(_translate("stroboPYgui", "connect"))
        self.h_disconnect_delay_btn.setText(_translate("stroboPYgui", "disconnect"))
        self.h_delay_status.setText(_translate("stroboPYgui", "ready to connect"))
        self.tabs.setTabText(self.tabs.indexOf(self.hardware_tab), _translate("stroboPYgui", "Hardware"))
        self.a_times_box.setTitle(_translate("stroboPYgui", "Time Options"))
        self.a_timefile_cb.setText(_translate("stroboPYgui", "From File"))
        self.a_timefile_btn.setText(_translate("stroboPYgui", "Folder"))
        self.label_3.setText(_translate("stroboPYgui", "Distribution"))
        self.label_4.setText(_translate("stroboPYgui", "Start"))
        self.label_20.setText(_translate("stroboPYgui", "End"))
        self.label_21.setText(_translate("stroboPYgui", "Number of Points"))
        self.a_file_box.setTitle(_translate("stroboPYgui", "File"))
        self.a_folder_btn.setText(_translate("stroboPYgui", "Folder"))
        self.label_65.setText(_translate("stroboPYgui", "Wavelength"))
        self.label_66.setText(_translate("stroboPYgui", "Power"))
        self.label_67.setText(_translate("stroboPYgui", "Spot Size"))
        self.label_68.setText(_translate("stroboPYgui", "Wavelength"))
        self.label_69.setText(_translate("stroboPYgui", "Spot Size"))
        self.label_70.setText(_translate("stroboPYgui", "Power"))
        self.a_filename_le.setText(_translate("stroboPYgui", "newfile"))
        self.label.setText(_translate("stroboPYgui", "Pump"))
        self.label_2.setText(_translate("stroboPYgui", "Probe"))
        self.a_acquire_box.setTitle(_translate("stroboPYgui", "Acquire Options"))
        self.label_5.setText(_translate("stroboPYgui", "Short Stage Time Zero"))
        self.label_6.setText(_translate("stroboPYgui", "Long Stage Time Zero"))
        self.label_7.setText(_translate("stroboPYgui", "Number of Shots"))
        self.label_8.setText(_translate("stroboPYgui", "Number of Sweeps"))
        self.label_9.setText(_translate("stroboPYgui", "Delay Type"))
        self.label_16.setText(_translate("stroboPYgui", "Current Sweep"))
        self.label_17.setText(_translate("stroboPYgui", "Current Time"))
        self.label_30.setText(_translate("stroboPYgui", "Pink Laser Time Zero"))
        self.a_calib_box.setTitle(_translate("stroboPYgui", "Calibration"))
        self.label_10.setText(_translate("stroboPYgui", "Pixel Low"))
        self.label_11.setText(_translate("stroboPYgui", "Wavelength"))
        self.label_12.setText(_translate("stroboPYgui", "Pixel High"))
        self.label_13.setText(_translate("stroboPYgui", "Wavelength"))
        self.a_use_calib.setText(_translate("stroboPYgui", "Use Calibration"))
        self.a_launch_box.setTitle(_translate("stroboPYgui", "Launch Run"))
        self.a_run_btn.setText(_translate("stroboPYgui", "Run"))
        self.a_test_run_btn.setText(_translate("stroboPYgui", "Test"))
        self.a_stop_btn.setText(_translate("stroboPYgui", "Stop"))
        self.groupBox_6.setTitle(_translate("stroboPYgui", "Plotting Options"))
        self.a_plot_log_t_cb.setText(_translate("stroboPYgui", "log time"))
        self.groupBox_7.setTitle(_translate("stroboPYgui", "Log"))
        self.a_cutoff_box.setTitle(_translate("stroboPYgui", "Cutoff"))
        self.a_use_cutoff.setText(_translate("stroboPYgui", "Use Cutoff"))
        self.label_15.setText(_translate("stroboPYgui", "Pixel High"))
        self.label_14.setText(_translate("stroboPYgui", "Pixel Low"))
        self.label_18.setText(_translate("stroboPYgui", "Measurement Progress"))
        self.label_19.setText(_translate("stroboPYgui", "Sweep Progress"))
        self.tabs.setTabText(self.tabs.indexOf(self.acquisition_tab), _translate("stroboPYgui", "Acquisition"))
        self.d_refmanip_box.setTitle(_translate("stroboPYgui", "Reference Manipulation"))
        self.d_use_ref_manip.setText(_translate("stroboPYgui", "Use Manipulation"))
        self.label_42.setText(_translate("stroboPYgui", "Vertical Stretch"))
        self.label_43.setText(_translate("stroboPYgui", "Vertical Offset"))
        self.label_44.setText(_translate("stroboPYgui", "Horizontal Offset"))
        self.label_45.setText(_translate("stroboPYgui", "Scale Center"))
        self.label_46.setText(_translate("stroboPYgui", "Scale Factor"))
        self.d_calib_box.setTitle(_translate("stroboPYgui", "Calibration"))
        self.label_23.setText(_translate("stroboPYgui", "Pixel Low"))
        self.label_24.setText(_translate("stroboPYgui", "Wavelength"))
        self.label_31.setText(_translate("stroboPYgui", "Pixel High"))
        self.label_32.setText(_translate("stroboPYgui", "Wavelength"))
        self.d_use_calib.setText(_translate("stroboPYgui", "Use Calibration"))
        self.d_acquire_box.setTitle(_translate("stroboPYgui", "Acquire Options"))
        self.label_35.setText(_translate("stroboPYgui", "Short Stage Time Zero"))
        self.label_36.setText(_translate("stroboPYgui", "Long Stage Time Zero"))
        self.label_39.setText(_translate("stroboPYgui", "Delay Type"))
        self.label_37.setText(_translate("stroboPYgui", "Number of Shots"))
        self.label_41.setText(_translate("stroboPYgui", "Spectrum Type"))
        self.d_use_ir_gain.setText(_translate("stroboPYgui", "IR Gain"))
        self.label_38.setText(_translate("stroboPYgui", "Pink Laser Time Zero"))
        self.label_22.setText(_translate("stroboPYgui", "dark correction shots x"))
        self.d_launch_box.setTitle(_translate("stroboPYgui", "Launch"))
        self.d_run_btn.setText(_translate("stroboPYgui", "Run"))
        self.d_stop_btn.setText(_translate("stroboPYgui", "Stop"))
        self.d_other_box.setTitle(_translate("stroboPYgui", "Other"))
        self.d_use_linear_corr.setText(_translate("stroboPYgui", "Linear Pixel Correction"))
        self.label_51.setText(_translate("stroboPYgui", "Threshold Pixel"))
        self.label_52.setText(_translate("stroboPYgui", "Threshold Value"))
        self.d_use_reference.setText(_translate("stroboPYgui", "Use Reference"))
        self.d_set_linear_corr_btn.setText(_translate("stroboPYgui", "Set"))
        self.d_use_avg_off_shots.setText(_translate("stroboPYgui", "Use Avg Off Shots"))
        self.label_53.setText(_translate("stroboPYgui", "Max dtt"))
        self.groupBox_17.setTitle(_translate("stroboPYgui", "Log"))
        self.d_cutoff_box.setTitle(_translate("stroboPYgui", "Cutoff"))
        self.d_use_cutoff.setText(_translate("stroboPYgui", "Use Cutoff"))
        self.label_33.setText(_translate("stroboPYgui", "Pixel Low"))
        self.label_34.setText(_translate("stroboPYgui", "Pixel High"))
        self.d_times_box.setTitle(_translate("stroboPYgui", "Time"))
        self.d_move_to_time_btn.setText(_translate("stroboPYgui", "Move to Time"))
        self.d_jogleft.setText(_translate("stroboPYgui", "<"))
        self.d_jogright.setText(_translate("stroboPYgui", ">"))
        self.d_set_current_btn.setText(_translate("stroboPYgui", "Set Current"))
        self.label_25.setText(_translate("stroboPYgui", "Red: Probe Shot to Shot"))
        self.label_26.setText(_translate("stroboPYgui", "Blue: Reference Shot to Shot"))
        self.label_27.setText(_translate("stroboPYgui", "Green: Probe over Reference"))
        self.tabs.setTabText(self.tabs.indexOf(self.diagnostics_tab), _translate("stroboPYgui", "Diagnostics"))
        self.tabs.setTabText(self.tabs.indexOf(self.log_tab), _translate("stroboPYgui", "Log"))

from pyqtgraph import ImageView, PlotWidget
